name: Build Test Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  ZIP_FILE: ${{ github.event.repository.name }}.zip
  LAMBDA_NAME: ${{ vars.LAMBDA_NAME }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        # The GitHub editor is 127 chars wide
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest main.py
    - name: Create zip package
      run: |
        pip install -r requirements.txt --target ./package
        cd package && zip -r ../$ZIP_FILE .
        cd ..
        zip $ZIP_FILE *.py
        unzip -l $ZIP_FILE
        ls -al $ZIP_FILE
    - name: Deploy AWS Lambda
      run: |
        aws lambda update-function-code --function-name $LAMBDA_NAME --zip-file fileb://$ZIP_FILE
